title: Python Basics
author: Arthur Koehl, Tyler Shoemaker, and Nick Ulle
copyright: "2022"
logo: img/datalab-logo-full-color-rgb-1.png
only_build_toc_files: true

repository:
  url: https://github.com/ucdavisdatalab/workshop_python_basics

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

execute:
  execute_notebooks: auto

html:
  use_repository_button: true

# Temporary workaround for title not showing in left navbar due to:
# <https://github.com/jupyter-book/jupyter-book/issues/2013>
sphinx:
  config:
    html_theme_options:
      logo:
        text: "Python Basics"
