[project]
authors = [
  "Nick Ulle <nick.ulle@gmail.com>",
  "Tyler Shoemaker",
  "Arthur Koehl"
]
channels = ["conda-forge", "main", "r", "msys2"]
description = "Reader for the Python Basics workshop series. "
name = "python-basics"
platforms = ["linux-64", "osx-64", "win-64"]
version = "2022.fall.0"  # <year>.<quarter>.<revision #>

[tasks]

[dependencies]
python = "3.10.*"
jupyter-book = "0.13.1.*"
ca-certificates = "*"
openssl = "*"
matplotlib = "*"
certifi = "*"
pandas = ">=1.4"
requests-cache = "*"
plotnine = ">=0.9"
ghp-import = "*"
