[project]
authors = [
  "Nick Ulle <nick.ulle@gmail.com>",
  "Tyler Shoemaker",
  "Arthur Koehl"
]
channels = ["conda-forge"]
description = "Reader for the Python Basics workshop series."
name = "python-basics"
platforms = ["linux-64", "osx-64", "win-64"]
version = "2022.fall.1"  # <year>.<quarter>.<revision #>

[tasks]

[dependencies]
python = ">=3.12.7,<4"
jupyter-book = ">=1.0.3,<2"
matplotlib = ">=3.9.2,<4"
pandas = ">=2.2.3,<3"
plotnine = ">=0.13.6,<0.14"
requests-cache = ">=1.2.1,<2"
requests = ">=2.32.3,<3"
numpy = ">=2.1.2,<3"
ghp-import = ">=2.1.0,<3"
